name: Releases

on: 
  push:
    tags:
    - 'v[0-9]+'

jobs:
  run-test:
    uses: ./.github/workflows/tests.yml

  create-branch:
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new branch
        run: |
          git checkout -b release-${{ github.ref_name }}
          git push -u origin release-${{ github.ref_name }}

  create-issue:
    needs: run-test
    if: ${{ !contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create issue
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
          AUTHOR: ${{ github.actor }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        with:
          assignees: ${{ github.actor }}
          update_existing: true
          search_existing: all
      - name: Close issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue close ${{ steps.create-issue.outputs.number }}
        
  build:
    needs: run-test
    if: ${{ !contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Make build
        run: |
          npm ci
          npm run build
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true,
          allowUpdates: true,
