name: Tests and Commitlint

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install
          npx jest --version
          npx playwright --version
      - name: Run tests
        run: |
          for commit in $(git rev-list ${{ github.event.before }}..${{ github.sha }}); do
            npm run test-ci
            npm run e2e-ci
          done
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install commitlint
        run: |
          npm ci
          npx commitlint --version
      - name: Validate current commit (last commit) with commitlint
        run: |
          for commit in $(git rev-list ${{ github.event.before }}..${{ github.sha }}); do
            npx commitlint --from HEAD~1 --to HEAD --verbose
          done
